add common command-line arguments, increase memory and cpu

diff --git a/src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/05-wait-for-config-version.yaml b/src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/05-wait-for-config-version.yaml
--- a/src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/05-wait-for-config-version.yaml
+++ b/src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/05-wait-for-config-version.yaml
@@ -17,24 +17,14 @@ spec:
             - /bin/sh
             - -c
           args:
-            - |
-              set -xe
-              CONFIG_VERSION_PATH="v1/features"
-
-              for i in 0 1 2
-              do
-                ADMIN_API_PATH="http://up-img-admin-mtls-${i}.up-img-admin-mtls.${POD_NAMESPACE}.svc.cluster.local.:9644"
-                CLUSTER_VERSION=$(curl -s ${ADMIN_API_PATH}/${CONFIG_VERSION_PATH} | jq -r .cluster_version)
-
-                NODE_LATEST_VERSION=$(curl -s ${ADMIN_API_PATH}/${CONFIG_VERSION_PATH} | jq -r .node_latest_version)
-
-                if [ "$CLUSTER_VERSION" -gt "$NODE_LATEST_VERSION" ]; then
-                  echo "failed: Cluster version is ${CLUSTER_VERSION} is greater than ${NODE_LATEST_VERSION}"
-                  exit 1
-                fi
-              done
-
-              echo "test passed"
+            - "set -xe\nCONFIG_VERSION_PATH=\"v1/features\"\n\nfor i in 0 1 2\ndo\n\
+              \  ADMIN_API_PATH=\"http://up-img-admin-mtls-${i}.up-img-admin-mtls.${POD_NAMESPACE}.svc.cluster.local.:9644\"\
+              \n  CLUSTER_VERSION=$(curl -s ${ADMIN_API_PATH}/${CONFIG_VERSION_PATH}\
+              \ | jq -r .cluster_version)\n\n  NODE_LATEST_VERSION=$(curl -s ${ADMIN_API_PATH}/${CONFIG_VERSION_PATH}\
+              \ | jq -r .node_latest_version)\n\n  if [ \"$CLUSTER_VERSION\" -gt \"\
+              $NODE_LATEST_VERSION\" ]; then\n    echo \"failed: Cluster version is\
+              \ ${CLUSTER_VERSION} is greater than ${NODE_LATEST_VERSION}\"\n    exit\
+              \ 1\n  fi\ndone\n\necho \"test passed\"\n"
       restartPolicy: Never
   backoffLimit: 2
   parallelism: 1
